SELECT MAX(SEQUENCE#)
, THREAD#
FROM V$ARCHIVED_LOG
WHERE RESETLOGS_CHANGE# = (
	SELECT MAX(RESETLOGS_CHANGE#)
	FROM V$ARCHIVED_LOG
)
GROUP BY THREAD#;

SELECT DESTINATION
, STATUS
, ARCHIVED_THREAD#
, ARCHIVED_SEQ#
FROM V$ARCHIVE_DEST_STATUS
WHERE STATUS <> 'DEFERRED'
AND STATUS <> 'INACTIVE';

