col db_name for a15;

select INST_ID
, SESSION_ID
, SESSION_NAME
, SESSION_STATE
, DB_NAME
, NUM_PROCESS
, START_SCN
, END_SCN
, SPILL_SCN
, PROCESSED_SCN
, PREPARED_SCN
, READ_SCN MAX_MEMORY_SIZE
, USED_MEMORY_SIZE PINNED_TXN
, PINNED_COMMITTED_TXN
from GV$LOGMNR_SESSION;

SELECT SESSION_ID, NAME, VALUE
FROM V$LOGMNR_STATS;

